# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Content

# Model Form Field configuration
form: $/wms/scontent/models/content/fields.yaml

# Model Class name
modelClass: Wms\Scontent\Models\Content

# Default redirect location
defaultRedirect: wms/scontent/contents

# Create page
create:
    title: Create Content
    redirect: wms/scontent/contents/update/:id
    redirectClose: wms/scontent/contents

# Update page
update:
    title: Edit Content
    redirect: wms/scontent/contents
    redirectClose: wms/scontent/contents

# Preview page
preview:
    title: Превью Content
