# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/wms/scontent/models/content/columns.yaml

# Model Class name
modelClass: Wms\Scontent\Models\Content

# List Title
title: Управление Contents

# Link URL for each record
recordUrl: wms/scontent/contents/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

showTree: true

treeExpanded: true

# Default sorting column
defaultSort:
   column: created_at
   direction: desc

# filter: config_filter.yaml

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
